### ISSUE TITLE
can't compile on linux

### ISSUE THREAD

**Issue by qicosmos** [pferdinand/libpqmxx#2]
I try to compile on ubuntu14.04, error occur, thi is the message:
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_TYPE_INCLUDE_DIR) (found
  version "9.3.13")
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindPostgreSQL.cmake:169 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)

**Comment by pferdinand** [comment]
Hi, it's a cmake bug. I switched to cmake 3.5 to fix it. The version of cmake currently in the CMakefile.txt repository is 3.8 because I'm trying to make it work on Travis but I'm facing the same issue. Also the Postgres library dependency is not libpqdev but the server one (I don't remember its name but you can find it in the Contribution section of the documentation)

**Comment by qicosmos** [comment]
ok, thanks.
